services:

  # ============================================================
  # SERVER SERVICE
  # ============================================================
  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: expense-server

    ports:
      - "5001:5000"

    env_file:
      - ./.env

    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

    # Start server AFTER db container starts (not db readiness)
    depends_on:
      - db

    command: ["npm", "run", "dev"]

    restart: unless-stopped


  # ============================================================
  # DATABASE SERVICE (PostgreSQL 16)
  # ============================================================
  db:
    image: postgres:16
    container_name: expense-db

    env_file:
      - ./.env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    restart: unless-stopped

  # ============================================================
  # CLIENT SERVICE (React))
  # ============================================================
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: expense-client

    ports:
      - "3000:3000"

    volumes:
      # Mounts your local client folder for hot-reloading
      - ./client:/usr/src/app
      # Anonymous volume for the container's node_modules
      - /usr/src/app/node_modules
    
    environment:
      # Fixes hot-reloading issues inside Docker
      - WDS_SOCKET_PORT=0

    depends_on:
      - server
    
    restart: unless-stopped
    
  

volumes:
  postgres_data:
